/*
 *  Document    : Supplier PostOrder.js
 *  Author      : Uyarchi
 *  Description : post order of Supplier
 */
import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Link from "next/link";
import { Breadcrumb } from "antd";
import {
  Table,
  Thead,
  Tbody,
  Tr,
  Th,
  Td,
  Button,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  ModalFooter,
  useDisclosure,
} from "@chakra-ui/react";
import { GoogleMap, LoadScript, Marker } from "@react-google-maps/api";
import Pagination from "../controls/Pagination";
import axios from "../../axios";
import AddRequirement from "./AddRequirement";
//useTable
const useTable = () => {
  const [Loading, setLoading] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [showLimit, setShowLimit] = useState(10);
  const [gridApi, setGridApi] = useState(null);
  const [rowData, setRowData] = useState(null);
  return {
    currentPage,
    showLimit,
    Loading,
    gridApi,
    rowData,
    setCurrentPage,
    setLoading,
    setShowLimit,
    setGridApi,
    setRowData,
  };
};
const Postorder = () => {
  //router
  const router = useRouter();
  //usestate
  const [reload, setreload] = useState(false);
  const [slat, setslat] = useState("");
  const [slng, setslng] = useState("");
  const [total, settotal] = useState("");

  //table
  const EmployeeTable = useTable();
  //get employees
  const fetchdata = async (page = 1) => {
    EmployeeTable.setLoading(true);
    const response = await axios.get("/v1/requirementCollectionBS/Supplier");
    if (response.status === 200 && response.data) {
      EmployeeTable.setRowData(response.data);
      settotal(response.data.count);
    } else {
      EmployeeTable.setRowData([]);
    }
  };
  //useEffect
  useEffect(() => {
    fetchdata(EmployeeTable.currentPage, EmployeeTable.showLimit);
  }, [reload, EmployeeTable.currentPage, EmployeeTable.showLimit]);
  //modal for order details
  //usestate
  const [isshopopen, setIsshopopen] = useState(false);
  const [supplier, setSupplier] = useState("");
  const isshopclose = () => {
    setIsshopopen(false);
  };
  const isopenshop = (props) => {
    setIsshopopen(true);
    axios
      .get(`/v1/requirementCollectionBS/Supplier/${props}`)
      .then((res) => setSupplier(res.data[0]));
  };
  //modal for map
  const { isOpen, onOpen, onClose } = useDisclosure();
  //mapview
  const isOpenmap = (props) => {
    onOpen();
    setslat(props.lat);
    setslng(props.lang);
  };
  const mapStyles = {
    height: "100%",
    width: "100%",
  };
  return (
    <>
      <Head>
        <title>Supplier/Buyer App - Manage Supplier Requirements</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="p-4 ">
        <div className="w-full pb-4">
          <Breadcrumb separator=">">
            <Breadcrumb.Item href="/home">Home</Breadcrumb.Item>
            <Breadcrumb.Item>Supplier Manage Requirements</Breadcrumb.Item>
          </Breadcrumb>
        </div>
        <hr className="p-1"></hr>
        <div className="flex items-center pb-4">
          <span className="flex-auto text-sky-500 text-xl">
            Supplier Manage Requirements
          </span>
          <div className="flex items-center gap-3">
            <AddRequirement setreload={setreload} reload={reload} />
            <Button colorScheme="blue" onClick={() => router.back()}>
              Back
            </Button>
            <Button colorScheme="blue" onClick={() => router.reload()}>
              Refresh
            </Button>
          </div>
        </div>
        <div className="border-gray-500 scroll-smooth border">
          <Table
            size="sm"
            scaleY="44"
            variant="striped"
            colorScheme="whatsapp"
            className="overflow-auto"
          >
            <Thead className="bg-headergreen">
              <Tr>
                <Th textAlign="center">S.No</Th>
                <Th textAlign="center">Date</Th>

                <Th textAlign="center">Id</Th>
                <Th textAlign="center">Name</Th>
                <Th textAlign="center">Product Name</Th>
                <Th textAlign="center">Map View</Th>
              </Tr>
            </Thead>
            <Tbody>
              {EmployeeTable.rowData != "" ? null : (
                <Tr>
                  <Td
                    style={{ textAlign: "center" }}
                    className="font-semibold"
                    colSpan="7"
                  >
                    No Data Found
                  </Td>
                </Tr>
              )}
              {EmployeeTable.rowData &&
                EmployeeTable.rowData.map((item, index) => (
                  <Tr key={index}>
                    <Td textAlign="center">{index + 1}</Td>
                    <Td textAlign="center">{item.date}</Td>
                    {/* <Td>{item.type}</Td> */}
                    <Td textAlign="center">{item.secretName}</Td>
                    <Td textAlign="center">
                      <Button
                        size="sm"
                        colorScheme="blue"
                        variant="link"
                        onClick={() => isopenshop(item._id)}
                      >
                        {item.name}
                      </Button>
                    </Td>
                    <Td textAlign="center">{item.product}</Td>
                    <Td textAlign="center">
                      <Button
                        size="sm"
                        colorScheme="blue"
                        variant="link"
                        onClick={() => isOpenmap(item)}
                      >
                        {item.stockLocation}
                      </Button>
                    </Td>
                  </Tr>
                ))}
            </Tbody>
          </Table>
        </div>
        <Pagination
          totalRecord={total ? total : 0}
          rowLength={EmployeeTable.rowData ? total : 0}
          {...EmployeeTable}
        />
        <Modal isOpen={isshopopen} onClose={isshopclose}>
          <ModalOverlay />
          <ModalContent>
            <ModalHeader>Orders Details</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
              <div className="border border-graycolor cursor-pointer">
                <div className="grid grid-cols-5 px-4">
                  <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                    Product Name
                  </div>
                  <div className="col-span-4 p-1">{supplier.product}</div>
                </div>
                <div className="grid grid-cols-5 px-4 border-t border-graycolor">
                  <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                    Stock Location
                  </div>
                  <div className="col-span-4 p-1">{supplier.stockLocation}</div>
                </div>
                <div className="grid grid-cols-5 px-4 border-t border-graycolor">
                  <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                    Stock Position
                  </div>
                  <div className="col-span-4 p-1">{supplier.stockPosition}</div>
                </div>
                {supplier.stockPosition === "ready" ? (
                  <>
                    <div className="grid grid-cols-5 px-4 border-t border-graycolor">
                      <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                        Packed Type
                      </div>
                      <div className="col-span-4 p-1">{supplier.packType}</div>
                    </div>
                    <div className="grid grid-cols-5 px-4 border-t border-graycolor">
                      <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                        Excepted Quantity
                      </div>
                      <div className="col-span-4 p-1">
                        {supplier.expectedQnty}
                      </div>
                    </div>
                    <div className="grid grid-cols-5 px-4 border-t border-graycolor">
                      <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                        Excepted Price
                      </div>
                      <div className="col-span-4 p-1">
                        {supplier.expectedPrice}
                      </div>
                    </div>
                  </>
                ) : (
                  <>
                    <div className="grid grid-cols-5 px-4 border-t border-graycolor">
                      <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                        Stock Availability Date
                      </div>
                      <div className="col-span-4 p-1">
                        {supplier.stockAvailabilityDate}
                      </div>
                    </div>
                    <div className="grid grid-cols-5 px-4 border-t border-graycolor">
                      <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                        Stock Availability Time
                      </div>
                      <div className="col-span-4 p-1">
                        {supplier.stockAvailabilityTime}
                      </div>
                    </div>
                  </>
                )}
                <div className="grid grid-cols-5 px-4 border-t border-graycolor">
                  <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                    Payment Mode
                  </div>
                  <div className="col-span-4 p-1">{supplier.paymentMode}</div>
                </div>
                {supplier.paymentMode == "advance" ? (
                  <div className="grid grid-cols-5 px-4 border-t border-graycolor">
                    <div className="col-span-1 text-blue-500 text-semibold border-r border-graycolor p-1">
                      Advance
                    </div>
                    <div className="col-span-4 p-1">{supplier.advance}</div>
                  </div>
                ) : null}
              </div>
            </ModalBody>
            <ModalFooter>
              <Button onClick={isshopclose} colorScheme="blue" mr={3}>
                Close
              </Button>
            </ModalFooter>
          </ModalContent>
        </Modal>
        <Modal isOpen={isOpen} onClose={onClose}>
          <ModalOverlay />
          <ModalContent>
            <ModalHeader>Map View</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
              {slat && slng ? (
                <div className="flex justify-center text-center">
                  <div className="object-cover h-48 w-96">
                    <LoadScript googleMapsApiKey="AIzaSyDoYhbYhtl9HpilAZSy8F_JHmzvwVDoeHI">
                      <GoogleMap
                        mapContainerStyle={mapStyles}
                        zoom={13}
                        center={{
                          lat: parseFloat(slat),
                          lng: parseFloat(slng),
                        }}
                      >
                        <Marker
                          position={{
                            lat: parseFloat(slat),
                            lng: parseFloat(slng),
                          }}
                        />
                      </GoogleMap>
                    </LoadScript>
                  </div>
                </div>
              ) : (
                <div>No coordinates Passed</div>
              )}
            </ModalBody>
            <ModalFooter>
              <Button onClick={onClose} colorScheme="blue" mr={3}>
                Close
              </Button>
            </ModalFooter>
          </ModalContent>
        </Modal>
      </div>
    </>
  );
};
export default Postorder;
